# Generated by Django 3.2.9 on 2021-11-25 21:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'db_table': 'barrio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Depeartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Etnia',
                'verbose_name_plural': 'Etnias',
                'db_table': 'etnia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Hobby',
                'verbose_name_plural': 'Hobbies',
                'db_table': 'hobby',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'pais',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Profesion',
                'verbose_name_plural': 'Profesiones',
                'db_table': 'profesion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.barrio')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'db_table': 'puesto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.cargo')),
            ],
            options={
                'verbose_name': 'Lider',
                'verbose_name_plural': 'Lideres',
                'db_table': 'lider',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Elector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cedula')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('fecha_nacimiento', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('date_registro', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('genero', models.CharField(max_length=10)),
                ('hijos', models.CharField(max_length=10)),
                ('ocupacion', models.CharField(max_length=50, verbose_name='Ocupacion')),
                ('fijo', models.CharField(max_length=10, unique=True, verbose_name='Telefono Fijo')),
                ('celular', models.CharField(max_length=10, unique=True, verbose_name='Telefono Celular')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('facebook', models.CharField(max_length=50, verbose_name='Facebook')),
                ('ciudad_v', models.CharField(max_length=50, verbose_name='Ciudad Votacion')),
                ('mesa', models.CharField(max_length=4, unique=True, verbose_name='Mesa')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('cvitae', models.FileField(blank=True, null=True, upload_to='cvitae/%Y/%m/%d')),
                ('validacion1', models.CharField(max_length=10)),
                ('validacion2', models.CharField(max_length=10)),
                ('validacion3', models.CharField(max_length=10)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.barrio')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.ciudad')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.depeartamento')),
                ('etnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.etnia')),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.hobby')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.lider')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.pais')),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.profesion')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.puesto')),
            ],
            options={
                'verbose_name': 'Elector',
                'verbose_name_plural': 'Electores',
                'db_table': 'elector',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='depeartamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.pais'),
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.ciudad')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'comuna',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.depeartamento'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.comuna'),
        ),
    ]
