# Generated by Django 3.2.9 on 2021-12-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0002_category_client_detsale_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elector',
            name='fijo',
            field=models.CharField(max_length=10, verbose_name='Telefono Fijo'),
        ),
    ]
