# Generated by Django 3.2.9 on 2021-12-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0003_alter_elector_fijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elector',
            name='mesa',
            field=models.CharField(max_length=4, verbose_name='Mesa'),
        ),
    ]
